### ISSUE TITLE
Add logic to get the factorial of the number

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#1]
Please describe the feature you want this project to offer
A route to provide the factorial of the number

Describe the solution you'd like
The route created should return the factorial of the required number

**Comment by iamuv2000** [comment]
Hey @ZiyanK I would like to solve this issue, could you please assign it to me?

**Comment by ZiyanK** [comment]
@iamuv2000 Sure. Go ahead! All the best :)
