### ISSUE TITLE
Add a route to check whether a number is a neon number or not

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#10]
Please describe the feature you want this project to offer
A route that can return whether a number is a neon number or not

Describe the solution you'd like
Adding logic to a '/neon' route which returns whether the number is neon or not

**Comment by i-aryan** [comment]
Hey, I'd like to do it.

**Comment by arhaanb** [comment]
Hi, I've sent you a pull request. Please check it out, thank you. :)

**Comment by ZiyanK** [comment]
Closed with pr #28
