### ISSUE TITLE
Add a route that checks if a number is a dudeney number

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#12]
Please describe the feature you want this project to offer
A route that can return whether a number is a dudeney number or not

Describe the solution you'd like
Adding logic to a '/dudeney' route which returns whether the number is dudeney or not

**Comment by noob-master147** [comment]
Created a PR #17
 
Happy Hacking 🤩 🥳

**Comment by SardulDhyani** [comment]
Please assign this issue to me, I'll do it. 🥳

**Comment by ZiyanK** [comment]
Issue solved with #17

**Comment by SardulDhyani** [comment]
Created a PR #31 
Added the Palindrome route controller.

Happy Hacking 😁🤓
