### ISSUE TITLE
Add logic for palindrome in routes.js

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#2]
Describe the bug
The logic for palindrome isn't currently present in the route '/palindrome'

To Reproduce

Route not working at the moment

Expected behavior
Should get a response whether the string or number is a palindrome or not

**Comment by abhinav72610** [comment]
hey @ZiyanK  i'm new to this community and want to work on this can youy assign me this

**Comment by ZiyanK** [comment]
Sure @abhinav72610 go ahead!

**Comment by abhinav72610** [comment]
@ZiyanK just want a help as i'm new to this ...i have added the logic for palindrome string but do i need to update anything else also

**Comment by abhinav72610** [comment]
i have submitted my pr if there issome error please let me know

**Comment by SardulDhyani** [comment]
Added PR #31 
Added the Palindrome route controller.

**Comment by faturachmanyusup** [comment]
I think this issue is closed

**Comment by ZiyanK** [comment]
This issue has been solved.
