### ISSUE TITLE
Create a Route For Disarium Number

### ISSUE THREAD

**Issue by noob-master147** [IEEE-VIT/playing-with-numbers-node#29]
Please describe the feature you want this project to offer
Add a route to find whether a number is Disarium Number or not.

Describe the solution you'd like
Adding logic to a '/disarium' route which returns whether the number is Disarium or not

**Comment by amey-g** [comment]
I've added the required route, pls check and merge if it's fine :)

**Comment by ZiyanK** [comment]
Issue solved with pr #32
