### ISSUE TITLE
Add logic for armstrong in routes.js

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#3]
**Please describe the feature you want this project to offer**
A route that can return whether a number is Armstrong or not

**Describe the solution you'd like**
Adding logic to an '/armstrong' route which returns whether the number is Armstrong or not

**Comment by Avn007** [comment]
hey @ZiyanK , can I work on this issue ?

**Comment by ZiyanK** [comment]
Sure! @Avn007 
All the best :)

**Comment by ZiyanK** [comment]
This issue has been resolved :+1:
