### ISSUE TITLE
Add logic for prime number in routes.js

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#4]
Please describe the feature you want this project to offer
A route that can return whether a number is prime or not

Describe the solution you'd like
Adding logic to an '/prime' route which returns whether the number is Armstrong or not

**Comment by HarshUdai** [comment]
hey @ZiyanK  i would like to work on this, this is my first contribution, can you assign this to me

**Comment by ZiyanK** [comment]
Sure. Go ahead @HarshUdai

**Comment by ZiyanK** [comment]
Issue was solved.
