### ISSUE TITLE
Add reverse string route in routes.js

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#5]
Please describe the feature you want this project to offer
A route that can return the reverse of a string/number

Describe the solution you'd like
Adding a '/reverse' route which sends the reverse of the string as a response

**Comment by nhcarrigan** [comment]
May I take this on?

**Comment by ZiyanK** [comment]
Sure. @nhcarrigan

**Comment by amey-g** [comment]
can I try this?

**Comment by faturachmanyusup** [comment]
Is this API just for number or not ?

**Comment by ZiyanK** [comment]
This issue has been resolved :+1:
