### ISSUE TITLE
Route to check Krishnamurthy number

### ISSUE THREAD

**Issue by jinicode** [IEEE-VIT/playing-with-numbers-node#50]
**Please describe the feature you want this project to offer**
To add a route to check if number is Krishnamurthy numbe.r

**Describe the solution you'd like**
Add logic to '/krishnamurthy' to check if number is Krishnamurthy number.
**Describe alternatives you've considered (Optional)**

**Additional context (Optional)**

**Comment by jinicode** [comment]
I have sent a pr #58 and performed all the tests. Please merge it .

**Comment by ZiyanK** [comment]
Done :+1:
