### ISSUE TITLE
Add eslint in project

### ISSUE THREAD

**Issue by LeonardoCamargo31** [IEEE-VIT/playing-with-numbers-node#53]
**Describe the feature you want this project to offer**
Writing pattern in code

**Describe the solution you would like**
Add to eslist library

**Comment by kumaranshu72** [comment]
@LeonardoCamargo31 I can pick this up

**Comment by BhupaliRane** [comment]
I have added eslint to my repo. Can you please assign this task to me

**Comment by BhupaliRane** [comment]
If it's correct can you please add hacktoberfest accepted label to it
