### ISSUE TITLE
Add a route that checks if a number is an automorphic number 

### ISSUE THREAD

**Issue by ZiyanK** [IEEE-VIT/playing-with-numbers-node#9]
Please describe the feature you want this project to offer
A route that can return whether a number is an automorphic number or not

Describe the solution you'd like
Adding logic to a '/automorphic' route which returns whether the number is automorphic or not

**Comment by iamuv2000** [comment]
Hey @ZiyanK could you assign this issue to me?

**Comment by jinicode** [comment]
Hey , I would love to work on this .
Happy Hacking.

**Comment by piyushverma001** [comment]
Hey @ZiyanK  I am working on it .

**Comment by piyushverma001** [comment]
Hey @ZiyanK I have made the changes kindly review my PR at #38.

Cheers!

**Comment by piyushverma001** [comment]
@ZiyanK This issue is resolved. Kindly review my PR at #38 and close this issue.

**Comment by piyushverma001** [comment]
@ZiyanK This issue is resolves. Kindly review my PR at #38  and close this issue.!

**Comment by ZiyanK** [comment]
Route for checking automorphic number is resolved at #38. Kindly review this PR. @piyushverma001
